### ISSUE TITLE
Update Book Detail Screen Data (ID, Status)

### ISSUE THREAD

**Issue by frenchy-mark** [Warthog710/church-library#15]
- ID currently shows ISBN, should show Local Library ID (3 digit code)
- Status currently shows "NOT IMPLEMENTED", should show "In", "Out", etc.

**Comment by frenchy-mark** [comment]
Committed against mark-testing branch for the status in the search by library code case.  However, multiple copies of the same book may be returned when searching by author, title, or ISBN.  For these non-unique cases, I would like status to show the number IN and number OUT.
e.g. "Status: 1 IN (Library Code: ###), 2 OUT"

This will take some doing.

**Comment by frenchy-mark** [comment]
@Warthog710 why are there two booktemplate.php files?  I made changes to booktemplate2.php as it is used in the inventory page flow.  However, the checkout path from the index.php page goes to booktemplate.php and appears (on cursory examination) to be the same as booktemplate2.php.  Why redundant pages?

**Comment by Warthog710** [comment]
The difference between these two pages is one accepts SESSION variables as
its search parameters for when the page loads and the other uses URL
variables. This is because viewResult.php is unable to store its variables
in the session because it is transmitted after the PHP has done its work.
You could probably make it so that these SESSION variables are not required
on booktemplate.php instead using URL variables. This would eliminate the
need for redundant pages. Definitely, something I will look into improving.

I should have time to work on my assigned tasks late tomorrow after I
complete my homework. I will make sure that I take a look at this. For now,
I will post it as an issue on Github.

**Comment by Warthog710** [comment]
@frenchy-mark 
Just in case you did not see my reply.
