### ISSUE TITLE
Prevent the user from checking out a book that is not currently in.

### ISSUE THREAD

**Issue by Warthog710** [Warthog710/church-library#32]
bookTemplate.php needs to be changed to prevent the user from checking out a book that is currently checked out.

**Comment by frenchy-mark** [comment]
@Warthog710 are you implementing this or am I?  If you're already working on this, please assign this to yourself.

**Comment by frenchy-mark** [comment]
@Warthog710 , I took a stab at it.  However, with my limited knowledge of PHP (and the more I learn, the less I like PHP...) I run into an error seeing as the $bookstatus variable hasn't been initialized yet since the sql query is executed further down the page/script.  I'm not sure if there is a way we could execute the query earlier, or pass in the status after the button press on the previous page, etc.

`<button type="submit" name="submit" class="button2" <?php if ($bookstatus == 'OUT') { ?> disabled <?php } ?> onclick="checkout()">Checkout</button>`

**Comment by Warthog710** [comment]
@frenchy-mark 
I'll look at it tomorrow. I think I know of a way that will get it to work.

**Comment by Warthog710** [comment]
@frenchy-mark 
Actually, I'll get it done tonight. Shouldn't take me long to implement.
